ProjectName := "software_design_backend"
MainFile := ./main.go
PROJECTBASE := $(shell pwd)
PROJECTBIN := $(PROJECTBASE)/bin


# CGO_ENABLED: 禁止使用 CGO,确保生成的 可执行文件不依赖于特定的 C 语言环境,便于跨平台
# GOOS=linux: 指定目标操作系统
# GOARCH=amd64: 指定目标指令集架构
build: clean
	@go mod tidy
	@CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -o $(PROJECTBIN)/$(ProjectName) $(MainFile)
	@chmod +x $(PROJECTBIN)/
	@cp config.json $(PROJECTBIN)/config.json

run:
	@$(PROJECTBIN)/$(ProjectName)

# go fmt: 用于格式话项目代码
fmt:
	@go fmt $(PROJECTBASE)/...
	@go mod tidy

# go vet: 静态分析代码
vet:
	@go vet $(PROJECTBASE)/...
	@go mod tidy

# $>/dev/null 表示丢弃标准输入和错误输出
clean:
	@rm -rf $(PROJECTBIN)/*

depend:
	go mod download
	go mod tidy

help:
	@echo "make build: 			构建项目"
	@echo "make fmt:   			格式化代码"
	@echo "make vet:   			静态代码分析"
	@echo "make clean: 			清除构建目标"
	@echo "make depend:  		下载依赖到本地缓存"

.PHONY: fmt clean vet
