// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: rec_sys.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRecResultReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	AddressId      int32                  `protobuf:"varint,2,opt,name=addressId,proto3" json:"addressId,omitempty"`
	TouristType    int32                  `protobuf:"varint,3,opt,name=touristType,proto3" json:"touristType,omitempty"`
	PriceSensitive int32                  `protobuf:"varint,4,opt,name=priceSensitive,proto3" json:"priceSensitive,omitempty"`
	LikeType       []int32                `protobuf:"varint,5,rep,packed,name=likeType,proto3" json:"likeType,omitempty"`
	TargetType     []int32                `protobuf:"varint,6,rep,packed,name=targetType,proto3" json:"targetType,omitempty"`
	AttentionType  []int32                `protobuf:"varint,7,rep,packed,name=attentionType,proto3" json:"attentionType,omitempty"`
	Update         bool                   `protobuf:"varint,8,opt,name=update,proto3" json:"update,omitempty"`
	Limit          int32                  `protobuf:"varint,9,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRecResultReq) Reset() {
	*x = GetRecResultReq{}
	mi := &file_rec_sys_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecResultReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecResultReq) ProtoMessage() {}

func (x *GetRecResultReq) ProtoReflect() protoreflect.Message {
	mi := &file_rec_sys_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecResultReq.ProtoReflect.Descriptor instead.
func (*GetRecResultReq) Descriptor() ([]byte, []int) {
	return file_rec_sys_proto_rawDescGZIP(), []int{0}
}

func (x *GetRecResultReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetRecResultReq) GetAddressId() int32 {
	if x != nil {
		return x.AddressId
	}
	return 0
}

func (x *GetRecResultReq) GetTouristType() int32 {
	if x != nil {
		return x.TouristType
	}
	return 0
}

func (x *GetRecResultReq) GetPriceSensitive() int32 {
	if x != nil {
		return x.PriceSensitive
	}
	return 0
}

func (x *GetRecResultReq) GetLikeType() []int32 {
	if x != nil {
		return x.LikeType
	}
	return nil
}

func (x *GetRecResultReq) GetTargetType() []int32 {
	if x != nil {
		return x.TargetType
	}
	return nil
}

func (x *GetRecResultReq) GetAttentionType() []int32 {
	if x != nil {
		return x.AttentionType
	}
	return nil
}

func (x *GetRecResultReq) GetUpdate() bool {
	if x != nil {
		return x.Update
	}
	return false
}

func (x *GetRecResultReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetRecResultResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteIdxList   []int32                `protobuf:"varint,1,rep,packed,name=siteIdxList,proto3" json:"siteIdxList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecResultResp) Reset() {
	*x = GetRecResultResp{}
	mi := &file_rec_sys_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecResultResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecResultResp) ProtoMessage() {}

func (x *GetRecResultResp) ProtoReflect() protoreflect.Message {
	mi := &file_rec_sys_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecResultResp.ProtoReflect.Descriptor instead.
func (*GetRecResultResp) Descriptor() ([]byte, []int) {
	return file_rec_sys_proto_rawDescGZIP(), []int{1}
}

func (x *GetRecResultResp) GetSiteIdxList() []int32 {
	if x != nil {
		return x.SiteIdxList
	}
	return nil
}

var File_rec_sys_proto protoreflect.FileDescriptor

const file_rec_sys_proto_rawDesc = "" +
	"\n" +
	"\rrec_sys.proto\x12\arec_sys\"\xa1\x02\n" +
	"\x0fGetRecResultReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\x12\x1c\n" +
	"\taddressId\x18\x02 \x01(\x05R\taddressId\x12 \n" +
	"\vtouristType\x18\x03 \x01(\x05R\vtouristType\x12&\n" +
	"\x0epriceSensitive\x18\x04 \x01(\x05R\x0epriceSensitive\x12\x1a\n" +
	"\blikeType\x18\x05 \x03(\x05R\blikeType\x12\x1e\n" +
	"\n" +
	"targetType\x18\x06 \x03(\x05R\n" +
	"targetType\x12$\n" +
	"\rattentionType\x18\a \x03(\x05R\rattentionType\x12\x16\n" +
	"\x06update\x18\b \x01(\bR\x06update\x12\x14\n" +
	"\x05limit\x18\t \x01(\x05R\x05limit\"4\n" +
	"\x10GetRecResultResp\x12 \n" +
	"\vsiteIdxList\x18\x01 \x03(\x05R\vsiteIdxList2T\n" +
	"\rRecSysService\x12C\n" +
	"\fGetRecResult\x12\x18.rec_sys.GetRecResultReq\x1a\x19.rec_sys.GetRecResultRespB\n" +
	"Z\b../pb;pbb\x06proto3"

var (
	file_rec_sys_proto_rawDescOnce sync.Once
	file_rec_sys_proto_rawDescData []byte
)

func file_rec_sys_proto_rawDescGZIP() []byte {
	file_rec_sys_proto_rawDescOnce.Do(func() {
		file_rec_sys_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rec_sys_proto_rawDesc), len(file_rec_sys_proto_rawDesc)))
	})
	return file_rec_sys_proto_rawDescData
}

var file_rec_sys_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rec_sys_proto_goTypes = []any{
	(*GetRecResultReq)(nil),  // 0: rec_sys.GetRecResultReq
	(*GetRecResultResp)(nil), // 1: rec_sys.GetRecResultResp
}
var file_rec_sys_proto_depIdxs = []int32{
	0, // 0: rec_sys.RecSysService.GetRecResult:input_type -> rec_sys.GetRecResultReq
	1, // 1: rec_sys.RecSysService.GetRecResult:output_type -> rec_sys.GetRecResultResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rec_sys_proto_init() }
func file_rec_sys_proto_init() {
	if File_rec_sys_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rec_sys_proto_rawDesc), len(file_rec_sys_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rec_sys_proto_goTypes,
		DependencyIndexes: file_rec_sys_proto_depIdxs,
		MessageInfos:      file_rec_sys_proto_msgTypes,
	}.Build()
	File_rec_sys_proto = out.File
	file_rec_sys_proto_goTypes = nil
	file_rec_sys_proto_depIdxs = nil
}
